---
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - restore_cache:
          keys:
          - node-modules-{{ checksum "package.json" }}

      - run: 
          name: Install & build
          command: |
            echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
            npm install

      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package.json" }}

      - deploy: 
          name: Publish to NPM
          command: npm publish

general:
  branches:
    only:
      - master
